# Generated by Django 3.0.3 on 2023-10-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.CharField(max_length=80)),
                ('nombre_2', models.CharField(max_length=80)),
                ('apellido_1', models.CharField(max_length=80)),
                ('apellido_2', models.CharField(max_length=80)),
                ('id_tipo_documento', models.CharField(choices=[('1', 'Cedula de ciudadania'), ('2', 'Permiso especial'), ('3', 'Pasaporte'), ('4', 'Cedula de extranjeria'), ('5', 'Tarjeta de identidad'), ('6', 'Registro civil')], default='1', max_length=1)),
                ('numero_documento', models.CharField(default='', max_length=80)),
                ('correo_sena', models.EmailField(max_length=254)),
                ('correo_soy_sena', models.EmailField(max_length=254)),
                ('celular_1', models.CharField(max_length=80)),
                ('celular_2', models.CharField(max_length=80)),
                ('id_rol', models.CharField(choices=[('1', 'Instructor de planta'), ('2', 'Instructor contratista'), ('3', 'Monitor')], default='1', max_length=1)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField(blank=True)),
                ('id_area_instrtuctor', models.CharField(choices=[('1', 'Software')], default='1', max_length=1)),
                ('firma_electronica', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(choices=[('1', 'Consumible'), ('2', 'Devolutivo')], default='1', max_length=1)),
                ('nombre_material', models.CharField(max_length=40)),
                ('modelo_material', models.CharField(max_length=40)),
                ('ubicacion_material', models.CharField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos')], default='1', max_length=1)),
                ('valor_material', models.IntegerField()),
                ('estado_material', models.CharField(choices=[('1', 'Disponible'), ('2', 'Prestamo'), ('3', 'Garantia'), ('4', 'Soporte'), ('5', 'De baja'), ('6', 'Entregado')], default='1', max_length=1)),
                ('especificacion_tecnica_material', models.CharField(max_length=150)),
                ('codigo_barras_original_material', models.IntegerField()),
                ('codigo_barras_sena_material', models.IntegerField()),
                ('fecha_ingreso_material', models.DateField(auto_now_add=True)),
                ('actualizacion_material', models.DateField(auto_now_add=True)),
                ('encargado_registrar_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_ingresar_consumible_sistema', to='App_SistemaGestionInventario.Usuario')),
                ('instructor_ecargado_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_material', to='App_SistemaGestionInventario.Usuario')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
