# Generated by Django 3.0.3 on 2023-10-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('1', 'Instructor de planta'), ('2', 'Instructor contratista'), ('3', 'Monitor')], default='1', max_length=1)),
                ('tipo_documento', models.CharField(choices=[('1', 'Cedula de ciudadania'), ('2', 'Permiso especial'), ('3', 'Pasaporte'), ('4', 'Cedula de extranjeria'), ('5', 'Tarjeta de identidad'), ('6', 'Registro civil')], default='1', max_length=1)),
                ('numero_documento', models.IntegerField()),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('correo_soy_sena', models.CharField(max_length=35)),
                ('primer_telefono', models.IntegerField()),
                ('segundo_telefono', models.IntegerField(blank=True, null=True)),
                ('numero_ficha', models.IntegerField(blank=True, null=True)),
                ('fecha_ingres_sistema', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterField(
            model_name='materiales',
            name='ubicacion_material',
            field=models.CharField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos'), ('8', 'No aplica')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='PrestamosConsumibles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion_prestamo', models.IntegerField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos'), ('8', 'No aplica')], default='8', max_length=1)),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('encargado_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Usuario')),
                ('material_otorgado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Materiales')),
                ('recibe_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Clientes')),
            ],
            options={
                'verbose_name': 'Prestamo consumible',
                'verbose_name_plural': 'Prestamos Consumibles',
            },
        ),
    ]
