# Generated by Django 3.0.3 on 2023-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0003_auto_20231015_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamosconsumibles',
            name='ubicacion_prestamo',
            field=models.CharField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos'), ('8', 'No aplica')], default='8', max_length=1),
        ),
    ]
