# Generated by Django 3.0.3 on 2023-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0004_auto_20231016_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='numero_ficha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
