# Generated by Django 3.0.3 on 2023-10-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0005_auto_20231016_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='segundo_apellido',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segundo_telefono',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
