# Generated by Django 3.0.3 on 2023-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0006_auto_20231016_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='codigo_barras_original_material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='codigo_barras_sena_material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='ubicacion_material',
            field=models.CharField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos'), ('8', 'No aplica'), ('9', 'Competencia')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='prestamosconsumibles',
            name='ubicacion_prestamo',
            field=models.CharField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos'), ('8', 'No aplica'), ('9', 'Competencia')], default='8', max_length=1),
        ),
    ]
