# Generated by Django 3.0.3 on 2023-10-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0007_auto_20231021_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamosconsumibles',
            old_name='encargado_registra',
            new_name='encargado_registra_prestamo_consumible',
        ),
        migrations.RenameField(
            model_name='prestamosconsumibles',
            old_name='fecha_entrega',
            new_name='fecha_entrega_prestamo_consumible',
        ),
        migrations.RenameField(
            model_name='prestamosconsumibles',
            old_name='material_otorgado',
            new_name='material_otorgado_prestamo_consumible',
        ),
        migrations.RenameField(
            model_name='prestamosconsumibles',
            old_name='recibe_prestamo',
            new_name='recibe_prestamo_prestamo_consumible',
        ),
        migrations.RenameField(
            model_name='prestamosconsumibles',
            old_name='ubicacion_prestamo',
            new_name='ubicacion_prestamo_prestamo_consumible',
        ),
        migrations.CreateModel(
            name='PrestamosDevolutivos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion_prestamo_material_devolutivo', models.CharField(choices=[('1', 'Bodega'), ('2', 'Zona 1'), ('3', 'Zona 2'), ('4', 'Zona 3'), ('5', 'Zona 4'), ('6', 'Zona 5'), ('7', 'Administrativos'), ('8', 'No aplica'), ('9', 'Competencia')], default='2', max_length=1)),
                ('fecha_entrega_material_devolutivo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_material_devolutivo', models.DateField()),
                ('encargado_registra_material_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Usuario')),
                ('material_otorgado_material_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Materiales')),
                ('recibe_prestamo_material_devolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SistemaGestionInventario.Clientes')),
            ],
        ),
    ]
