# Generated by Django 3.0.3 on 2023-10-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0008_auto_20231021_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamosdevolutivos',
            old_name='material_otorgado_material_devolutivo',
            new_name='material_otorgado_devolutivo',
        ),
    ]
