# Generated by Django 3.0.3 on 2023-10-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0009_auto_20231021_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1),
        ),
    ]
