# Generated by Django 3.0.3 on 2023-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SistemaGestionInventario', '0011_auto_20231022_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamosdevolutivos',
            options={'verbose_name': 'Prestamo Devolutivo', 'verbose_name_plural': 'Prestamos Devolutivos'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo_soy_sena',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero_documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='primer_telefono',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_documento',
            field=models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('P.E', 'Permiso especial'), ('Pasaporte', 'Pasaporte'), ('C.E', 'Cédula de extranjería'), ('T.I', 'Tarjeta de identidad'), ('R.C', 'Registro civil')], default='C.C', max_length=11),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='codigo_barras_original_material',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='codigo_barras_sena_material',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='estado_material',
            field=models.CharField(choices=[('Dis', 'Disponible'), ('Pres', 'Préstamo'), ('Gara', 'Garantía'), ('Sop', 'Soporte'), ('DB', 'De baja'), ('Entr', 'Entregado')], default='Dis', max_length=6),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular_1',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_sena',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_soy_sena',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_documento',
            field=models.CharField(choices=[('C.C', 'Cédula de ciudadanía'), ('P.E', 'Permiso especial'), ('Pasaporte', 'Pasaporte'), ('C.E', 'Cédula de extranjería'), ('T.I', 'Tarjeta de identidad'), ('R.C', 'Registro civil')], default='C.C', max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
